---
title: "FigureS3 + S3 - No Treatment and Wounding Leaf mV"
---
## Loading Packages
- Package files and their corresponding manuals can be found in the '02_Packages' folder

```{r include=TRUE, message=FALSE, echo=TRUE}
library(readxl) #needed for loading xlsx file
library(tidyverse) #contains ggplot2, dplyr, tidyr, readr, purrr, tibble, stringr, forcats packages 
library(ggpubr) #requires tidyverse to be loaded first, needed for graphs (e.g. ggboxplot function)
```

#Sensor Data - Leaf surface mV
```{r include=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
SensorData<-read_excel("TableS2.xlsx",sheet = "Sensor-leafmV", col_types = c("text", "numeric","numeric","numeric","numeric","text")) # loading excel, defining which sheet is loaded and defining the type of each column
#SensorData <- na.omit(SensorData) #removes all rows with NA - found in some of WM-12 data
SensorData$Cultivar <- factor(SensorData$Cultivar, levels = c("Beryl", "G122", "Eldorado", "ICA Bunsi", "Montrose", "Othello","WM-1","WM-12")) #order the Cultivars (for graph later on)
```

## Splitting Data by Block - Blocks 1-3: No Treatment, Block 4: Wounding Treatment
```{r include=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
SensorWound<- SensorData%>% filter(Block == 4) #Create a new table from SensorData that just has Block 4 (wounding) - will be used for Figure S3
SensorData<- SensorData %>% filter(Block < 4) #removes Block 4 from SensorData (Wounded Treatment)- will be used for Figure S2
```

# Fig. S2 - No Treatment - Leaf mV
```{r echo=FALSE}
SensorData$Leaf <-factor(SensorData$Leaf, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9"))  #defines Leaf number as a factor, needed to ensure that the group below can be grouped by Leaf
FigS2<-ggboxplot(SensorData,"Cultivar", "mV", color = "Leaf", palette="grey", title="Sensor - Leaf Surface mV") + #facet.by = group plots by TimePoint (pre and post), and group by color = Leaf, palette is greyscale
ylab("Millivolt (mV)") + #renam y axis
xlab("") + #blank out x axis label
theme(axis.text.x = element_text(size=12,angle = 90,vjust = 0.4, hjust=1)) + # x axis font size + change orientation of x axis labels
theme(axis.text.y = element_text(size=12))+ # y axis font size
theme(panel.grid.major.y = element_line(colour = "grey", linetype="dashed",size=0.5), panel.grid.minor.x = element_line(colour="grey", linetype="blank")) + #adding grid lines to graph, minor grids (0.5) are blank to remove them
theme(plot.title = element_text(hjust = 0.4, vjust=2)) + #Centering title
guides(colour = guide_legend(nrow = 1)) #legend below all 1 line instead of 2 lines
FigS2<-ggpar(FigS2, legend = "bottom") # Legend at bottom
FigS2<- annotate_figure(FigS2, top = text_grob("No Treatment", color = "black", face = "bold", size = 14)) #Adding a main title above the panels
FigS2
```

## Saving Fig. S2 as a tiff and pdf
```{r eval=FALSE, include=FALSE}
ggsave(plot=FigS2, file="FigS2-NoTreatment-LeafmV.tiff", units="in", width=11, height=7.5, dpi=300,compression='lzw')
ggsave(plot=FigS2, file="FigS2-NoTreatment-LeafmV.pdf", units="in", width=11, height=7.5, dpi=300)
```

# Fig. S3 - Leaf mV Pre- and Post-wounding
```{r echo=FALSE}
SensorWound$Leaf <-factor(SensorWound$Leaf, levels = c("1", "2", "3")) #defines Leaf number as a factor, needed to ensure that the group below can be grouped by Leaf
FigS3<-ggboxplot(SensorWound,"Cultivar", "mV",facet.by = "TimePoint", color = "Leaf", palette="grey", title="Sensor - Leaf Surface mV") + #facet.by = group plots by TimePoint (pre and post), and group by color = Leaf, palette is greyscale
ylab("Millivolt (mV)") + #renam y axis
xlab("") + #blank out x axis label
theme(axis.text.x = element_text(size=12,angle = 90,vjust = 0.4, hjust=1)) + # x axis font size + change orientation of x axis labels
theme(axis.text.y = element_text(size=12))+ # y axis font size
theme(panel.grid.major.y = element_line(colour = "grey", linetype="dashed",size=0.5), panel.grid.minor.x = element_line(colour="grey", linetype="blank")) + #adding grid lines to graph, minor grids (0.5) are blank to remove them
theme(plot.title = element_text(hjust = 0.5, vjust=2)) #Centering title
FigS3<-ggpar(FigS3, legend = "bottom") # Legend at bottom
FigS3<-FigS3+facet_grid(rows=vars(TimePoint)) #Creates 2 rows of graphs of Pre and Post
FigS3<- annotate_figure(FigS3, top = text_grob("Wounding Treatment", color = "black", face = "bold", size = 14)) #Adding a main title above the panels
FigS3
```

## Saving Fig. S3 as a tiff and pdf
```{r eval=FALSE, include=FALSE}
ggsave(plot=FigS3, file="FigS3-Wounded-mV.tiff", units="in", width=11, height=7.5, dpi=300,compression='lzw')
ggsave(plot=FigS3, file="FigS3-Wounded-mV.pdf", units="in", width=11, height=7.5, dpi=300)
```
